---
# Sysible defaults for the Calamares install-to-disk flow.
defaultGroups:
    - sudo
    - kvm
    - libvirt
    - docker
    - wireshark
    - plugdev
    - netdev
    - video
    - audio
autologinGroup: autologin
doAutologin: false
sudoersGroup: sudo
setRootPassword: true
doReusePassword: false
availableShells: /bin/bash
